---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    prod_clusterlogin: &prod_clusterlogin
      hostname: "{{ ProdCluster }}"
      username: "{{ ONTAP_cred.user }}"
      password: "{{ ONTAP_cred.password }}"
      https: true
      validate_certs: no
  tasks:
    - name: Add ACL
      netapp.ontap.na_ontap_cifs_acl:
          state: present
          share_name: "{{ Share }}"
          user_or_group: "{{ item.usergroup }}"
          type: "{{ item.type }}"
          permission: "{{ item.Permission }}"
          vserver: "{{ vservername }}"
          <<: *prod_clusterlogin
      when: acljob == 'Add ACL'
      loop: "{{ addacl }}"
    - name: Remove ACL
      netapp.ontap.na_ontap_cifs_acl:
          state: absent    
          vserver: "{{ vservername }}"
          user_or_group: "{{ item['User or Group'] }}"
          type: "{{ item.Type }}"
          permission: "{{ item.Permission }}"
          share_name: "{{ Share }}"
          <<: *prod_clusterlogin
      loop: "{{ acl }}"
      when: acljob == 'Remove ACL'
    
    