---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    prod_clusterlogin: &prod_clusterlogin
      hostname: "{{ ProdCluster }}"
      username: "{{ ONTAP_cred.user }}"
      password: "{{ ONTAP_cred.password }}"
      https: true
      validate_certs: no
  tasks:
    - name: Create Snapshot
      netapp.ontap.na_ontap_snapshot:
          state: present
          volume: "{{ Volume }}"         
          vserver: "{{ vservername }}"
          <<: *prod_clusterlogin
          snapshot: "{{ snapname }}"
      when: snapjob == 'Create Snapshot'
    - name: Delete Snapshots
      netapp.ontap.na_ontap_snapshot:
          state: absent
          volume: "{{ Volume }}"         
          vserver: "{{ vservername }}"
          <<: *prod_clusterlogin
          snapshot: "{{ item }}"
      loop: "{{ listsnaps }}"
      when: snapjob == 'Delete Snapshot'
    
    